### PR TITLE
Create snaps-boot CI environment on AWS

### PR DESCRIPTION
**Pull request by spisarski**
#### What does this PR do?
Creates an environment from which an image can be created and used for testing snaps-boot 
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
run it
#### Any background context you want to provide?
since creating a similar CI job to snaps-boot, I decided it was time to share this environment
#### Questions:
- Have you connected this PR to the issue it resolves?
n/a
- Does the documentation need an update?
It could be improved
- Does this add new Python dependencies?
no
- Have you added unit or functional tests for this PR?
no
- Does this patch update any configuration files?
no

### CODE REVIEW

**Comment by spisarski** [comment]
@bo-quan - purposely did not use a spot instance as this script is really for spinning up a machine that is ready to go, create a new image, and delete. We could however change this to a VM but the cost difference factoring the time for building it is most likely a wash.

**Comment by bo-quan** [comment]
@spisarski gotcha. Let me know when it's ready to go.

**Comment by spisarski** [comment]
Hoping to get boot & hb CI working with it, so I may need to make a minor adjustment or two...

**Comment by spisarski** [comment]
Complete, please review

**Comment by spisarski** [comment]
Please review
@bo-quan - the CI job will need to be tweaked to execute this

**Pull request merged**
